server:
  port: 9991

cxf:
  contextPath: /core

dao:
  mongo:
    host: localhost
    port: 27017
    options:
      ssl:
        enabled: false
        invalidHostnameAllowed: false
    dbName: queue-triage
    failedMessage:
      name: failedMessage

jms:
  activemq:
    brokers:
      - name: internal-broker
        url: tcp://localhost:61616
        queue: ActiveMQ.DLQ
        resend:
          frequency: 60
          timeUnit: SECONDS
