dao:
  mongo:
    failedMessage:
      password: "VAULT(queue-triage/mongo-dao/failedMessageUser)"

vault:
  address: http://localhost:1234/vault
  openTimeout: 20 #seconds
  readTimeout: 20 #seconds
  tokenAuthentication:
    tokenPath: classpath:.vault
